version: '3.3'

volumes:
  pg_data_foodgram:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data

  backend:
    image: theosmi808/foodgram_backend:latest
    env_file: ../.env
    depends_on:
      - db
    volumes:
      - ../static/:/app/static/
      - ../media/:/app/media/

  frontend:
    image: theosmi808/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    depends_on:
      - db
      - backend
      - frontend
    ports:
      - '8000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../static/:/var/html/static/
      - ../media/:/var/html/media/
