# Generated by Django 2.2.19 on 2023-10-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20231017_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='units',
            new_name='measurement_unit',
        ),
    ]
